# This is a TOML document.

[core]
maxLoad = 70

[core.cors]
enabled = false
allowedOrigins = ["*"]
allowedMethods = ["GET", "POST", "HEAD"]
allowedHeaders = ["X-Requested-With", "Content-Type", "Accept", "Origin"]
preflightMaxAge = 1800
allowCredentials = true
exposedHeaders = ""

[route."/"]
  option1 = 127

  [route."/".cors]
  enabled = true
